### ISSUE TITLE
KL Thresholding

### ISSUE THREAD

**Issue by fhrzn** [seongminp/transformers-into-vaes#5]
Hello again!
Thank you for the great code. As stated in the paper, there is a KL Thresholding technique. But, I feel lost looking for this function in the code. Could you please point out where I could find it?

Thank you very much!

**Comment by seongminp** [comment]
Hi! `T5VAE` has a attribute [`min_z`](https://github.com/seongminp/transformers-into-vaes/blob/master/model_t5.py#L35) that it uses to enforce KL thresholding on [this](https://github.com/seongminp/transformers-into-vaes/blob/master/model_t5.py#L212) line.

**Comment by fhrzn** [comment]
Got it, thank you very much! 👍
